spring:
  application:
    name: sboot-doe-aqui-monolith

  datasource:
    url: jdbc:mysql://localhost:3306/dbDoeAqui?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/dbDoeAquiGeo

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET:secret}